baseURL = "https://kornilakis.com/"
defaultContentLanguage = "en"
languageCode = "en"
theme = "LoveIt"
title = "The Curious Coder"
[Permalinks]
posts = ":year/:month/:filename"
[author]
email = ""
link = ""
name = "Alexis K"
[markup.highlight]
noClasses = false
[[menu.main]]
identifier = "posts"
name = "Posts"
post = ""
pre = ""
title = ""
url = "/posts/"
weight = 1
[[menu.main]]
identifier = "categories"
name = "Categories"
post = ""
pre = ""
title = ""
url = "/categories/"
weight = 2
[[menu.main]]
identifier = "webcompiled"
name = "WebCompiled"
post = ""
pre = ""
title = ""
url = "https://webcompiled.tech"
weight = 3
[[menu.main]]
identifier = "resume"
name = "Resume"
post = ""
pre = ""
title = ""
url = "/resume"
weight = 4
[params]
dateFormat = "2006-01-02"
defaultTheme = "auto"
description = "This is My New Hugo Site"
fingerprint = ""
gitRepo = ""
images = ["/logo.png"]
keywords = ["Theme", "Hugo"]
version = "0.2.X"
[params.analytics]
enable = true
[params.analytics.google]
anonymizeIP = true
id = "G-0WH584XEK3"
[params.app]
iconColor = "#5bbad5"
noFavicon = true
svgFavicon = ""
themeColor = "#ffffff"
tileColor = "#da532c"
title = "LoveIt"
[params.footer]
author = true
copyright = true
custom = ""
enable = true
hugo = false
icp = ""
license = "<a rel=\"license external nofollow noopener noreffer\" href=\"https://creativecommons.org/licenses/by-nc/4.0/\" target=\"_blank\">CC BY-NC 4.0</a>"
since = 2021
[params.header]
desktopMode = "fixed"
mobileMode = "auto"
[params.header.title]
logo = ""
name = "The Curious Coder"
post = ""
pre = ""
typeit = false
[params.home]
rss = 10
[params.home.posts]
defaultHiddenFromHomePage = false
enable = true
paginate = 6
[params.home.profile]
avatarURL = "/images/me.jpg"
disclaimer = ""
enable = true
gravatarEmail = ""
social = true
subtitle = "Software Engineer"
title = "Alexandros Kornilakis"
typeit = true
[params.list]
dateFormat = "01-02"
paginate = 20
rss = 10
[params.search]
absoluteURL = false
contentLength = 4000
enable = true
highlightTag = "em"
maxResultLength = 10
placeholder = ""
snippetLength = 30
type = "lunr"
[params.search.algolia]
appID = ""
index = ""
searchKey = ""
[params.section]
dateFormat = "01-02"
paginate = 20
rss = 10
[params.social]
Email = "info [at] alexisk.tech"
GitHub = "CuriouzK0d3r"
Linkedin = "kornilak"
RSS = true
Twitter = ""
